name: CI

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.0

      - name: Enable PrepareMetalShaders plugin
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidation -bool YES

      - name: Resolve dependencies
        run: swift package resolve

      - name: Test
        run: |
          xcodebuild test \
            -scheme files-to-chat-swift \
            -destination 'platform=macOS' \
            -derivedDataPath ./dist \
            -skipPackagePluginValidation ENABLE_PLUGIN_PREPAREMLSHADERS=YES

      - name: Build
        run: |
          xcodebuild build \
            -scheme files-to-chat-swift \
            -configuration Release \
            -destination 'platform=macOS' \
            -derivedDataPath ./dist \
            -skipPackagePluginValidation ENABLE_PLUGIN_PREPAREMLSHADERS=YES

      - name: Prepare artifact
        run: |
          cd ./dist/Build/Products/Release
          mv files-to-chat-swift files-to-chat
          chmod +x files-to-chat
          if [ -e mlx-swift_Cmlx.bundle/Contents/Resources/default.metallib ]; then
            cp mlx-swift_Cmlx.bundle/Contents/Resources/default.metallib .
          fi
          zip -r files-to-chat.macos.arm64.zip files-to-chat default.metallib || zip -r files-to-chat.macos.arm64.zip files-to-chat

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        env:
          CURRENT_DATE: ${{ env.CURRENT_DATE }}
        with:
          tag: nightly
          name: "Nightly Build ${{ env.CURRENT_DATE }}"
          draft: false
          prerelease: true
          allowUpdates: true
          artifacts: ./dist/Build/Products/Release/files-to-chat.macos.arm64.zip
          token: ${{ secrets.GITHUB_TOKEN }}
